require("plugins.treesitter-config")
require("plugins.neo-tree-config")
require("plugins.bufferline-config")
require("plugins.tokyonight-config")
require("plugins.cmp-config")
require("plugins.mason-config")
-- require("plugins.java-config")
-- require("plugins.neoconf-config")
require("plugins.lsp")
require("plugins.toggleterm-config")
require("plugins.autopairs-config")
require("plugins.ts-autotag-config")
require("plugins.lualine-config")
require("plugins.zen-mode-config")
require("plugins.telescope-config")
require("plugins.notify-config")
require("plugins.noice-config")
require("plugins.indent-blankline-config")
require("plugins.comment-config")
require("plugins.dashboard-config")
require("plugins.neorg-config")
